export enum ActionType {
  // Portfolio Action Types
  SET_PORTFOLIO_LOADING = 'SET_PORTFOLIO_LOADING',
  GET_PORTFOLIO = 'GET_PORTFOLIO',
  DELETE_PORTFOLIO_COIN = 'DELETE_PORTFOLIO_COIN',

  // Single Coin Action Types
  GET_COIN = 'GET_COIN',
  SET_COIN_LOADING = 'SET_COIN_LOADING',

  // Search Action Types
  SEARCH_COINS = 'SEARCH_COINS',
  SET_SEARCH_LOADING = 'SET_SEARCH_LOADING',
  SET_SEARCH_FAILED = 'SET_SEARCH_FAILED',

  // Preferences Action types
  GET_PREFERENCES = 'GET_PREFERENCES',
  SET_THEME = 'SET_THEME',
  SET_CURRENCY = 'SET_CURRENCY',
}
